fos_ck_editor:
    configs:
        main_config:
            toolbar:
              - {
                  name: "styles",
                  itesms:
                    [
                        "Bold",
                        "Italic",
                        "Underline",
                        "Strike",
                        "Blockquote",
                        "-",
                        "Link",
                        "-",
                        "RemoveFormat",
                        "-",
                        "NumberedList",
                        "BulletedList",
                        "-",
                        "Outdent",
                        "Indent",
                        "-",
                        "-",
                        "JustifyLeft",
                        "JustifyCenter",
                        "JustifyRight",
                        "JustifyBlock",
                        "-",
                        "Image",
                        "Table",
                        "-",
                        "Style",
                        "Format",
                        "Font",
                        "FontSize",
                        "-",
                        "TextColor",
                        "BGColor",
                        "Source",
                    ],
              }